### ISSUE TITLE
Calculator feature of 'Ocean's Pencil Case' not working

### ISSUE THREAD

**Issue by seowth** [OceanUwU/oceanmod#1]
Hello,

I did not use your old, pre-merge 'Calculator' mod, but it does not seem to be working in the current 'Ocean's Pencil Case' compilation.

- Modlist + Note: missing 'Calculator' icon 

![20230128155854_1](https://user-images.githubusercontent.com/87141050/215293192-7c416d8a-b607-4c72-be82-8c8fd0c772fe.jpg)

- Test: disabled 'Whiteboard' feature in-case it was blocking the calculator... 

![20230128160045_1](https://user-images.githubusercontent.com/87141050/215293342-25fa7312-e669-4242-8424-433e718a9417.jpg)

- ...no change: calculator still missing

![20230128160229_1](https://user-images.githubusercontent.com/87141050/215293417-dc2f1356-1a15-4f24-b0a3-65721cd29398.jpg)

- Thank you; 'Ocean's Pencil Case' is awesome! :)

**Comment by OceanUwU** [comment]
thanks for the report! fixed it and will update on steam tomorrow
