### ISSUE TITLE
"Special" Curse Cards Using Incorrect Card Frame Color

### ISSUE THREAD

**Issue by seowth** [OceanUwU/oceanmod#2]
The four curses affected are: ["Ascender's Bane"; "Curse of the Bell"; "Necromonicurse"; "Pride"] 

- These cards share the same card frames as "Special" 'Colorless' cards rather than using the set color for the 'Curse' card frame...

![20230128055904_1](https://user-images.githubusercontent.com/87141050/215318901-e45d3d63-d1ae-424f-b462-9a5c9de1d08e.jpg)

... i.e. They use the config for 'Special' rather than 'Curses'

**Comment by OceanUwU** [comment]
this is correct. these "special" curses are defined as special by the game because they can only be obtained by special means, and not from random curse generation, like from cursed key, or the match and keep event.

**Comment by seowth** [comment]
Noted, 
I just felt that to the undiscerning eye they appear like "positive" cards when they're the opposite...
...Though since it's a base game classification, it might be best not to mess with them(?)

I have my specials set to a neutral color so I am content :)
Thank you for attending to both of the issues I opened!

**Comment by OceanUwU** [comment]
someone else asked about this so v1.0.13 has an (off by default) option in the config to make this behave as you expected
